### ISSUE TITLE
Republish with new github name

### ISSUE THREAD

**Issue by matheus23** [jasonliang512/elm-heroicons#1]
Hi! I'm using this package in one of my applications. I can't build the new version, as you changed your username from `jasonliang512` to `jasonliang-dev`. This messes up some checksums.

Can you republish this package so it's in the elm package registry under the name `jasonliang-dev/elm-heroicons`?

Thanks!

**Comment by jasonliang-dev** [comment]
Hey 👋 I've been scratching my head for the past few days trying to find the best solution for this issue. It seems to be that the best thing I can do right now is to republish the package under my new username.

[`jasonliang-dev/elm-heroicons` is now published](https://package.elm-lang.org/packages/jasonliang-dev/elm-heroicons/latest/). I wish I could somehow remove/update `jasonliang512/elm-heroicons` on the package registry though.

**Comment by matheus23** [comment]
> I wish I could somehow remove/update jasonliang512/elm-heroicons on the package registry though.

I agree. It makes sense that the elm package repository is immutable, as then it would be possible to install elm packages forever (in theory), but in practice it's so tightly linked to github, it doesn't make sense that it's immutable.

Evan said he is working on a solution for this, but it's a large issue.
